import React from "react";
import avatar1 from '../../../../ad-images/avatar-1.png';
import avatar2 from '../../../../ad-images/avatar-2.png';
import avatar3 from '../../../../ad-images/avatar-3.png';
import house1 from '../../../../ad-images/house-1.jpg';
import house2 from '../../../../ad-images/house-2.jpg';
import house3 from '../../../../ad-images/house-3.jpg';
export const recentList = [
  {
    id: 1,
    avatar: avatar1,
    title: 'برای تنظیم سریع به پشتیبانی سریع نیاز دارید',
    description: [<span className="gx-link" key={1}>زیبا حسنی</span>, "  15 دقیقه قبل بلیط ایجاد کرد"],
    status: 2
  }, {
    id: 2,
    avatar: avatar2,
    title: 'پرس و جو پیش فروش در مورد محصول',
    description: [<span className="gx-link" key={2}>شما</span>, " جواب دادید 2 روز پیش"],
    status: 1
  }, {
    id: 3,
    avatar: avatar3,
    title: 'با توجه به خدمات سفارشی سازی',
    description: [<span className="gx-link" key={3}>زیبا حسنی</span>, " جواب دادید 2 روز پیش"],
    status: 4
  }
];

export const popularList = [
  {
    id: 1,
    image: house1,
    isFeatured: false,
    title: 'سمت ساحل ویلا ',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 3,
    baths: 3,
    area: '1400 متر مربع',
    more: 1,
  },
  {
    id: 2,
    image: house2,
    isFeatured: false,
    title: 'خانه خانوادگی لوکس در کنار ساحل',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 2,
    baths: 2,
    area: '1100 متر مربع',
    more: 2,
  },
  {
    id: 3,
    image: house3,
    isFeatured: false,
    title: 'خانه های سبک زندگی',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 4,
    baths: 1,
    area: '1300 متر مربع',
    more: 4,
  }
];
export const newJersy = [
  {
    id: 1,
    image: house1,
    isFeatured: false,
    title: 'خانه خانوادگی لوکس در کنار ساحل',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 3,
    baths: 3,
    area: '1400 متر مربع',
    more: 1,
  },
  {
    id: 2,
    image: house2,
    isFeatured: false,
    title: 'خانه های سبک زندگی',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 2,
    baths: 2,
    area: '1100 متر مربع',
    more: 2,
  },
  {
    id: 3,
    image: house3,
    isFeatured: false,
    title: 'سمت ساحل ویلا ',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 4,
    baths: 1,
    area: '1300 متر مربع',
    more: 4,
  }
];
export const colorado = [
  {
    id: 1,
    image: house1,
    isFeatured: false,
    title: 'خانه خانوادگی لوکس در کنار ساحل',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 3,
    baths: 3,
    area: '1400 متر مربع',
    more: 1,
  },
  {
    id: 2,
    image: house2,
    isFeatured: false,
    title: 'سمت ساحل ویلا ',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 2,
    baths: 2,
    area: '1100 متر مربع',
    more: 2,
  },
  {
    id: 3,
    image: house3,
    isFeatured: false,
    title: 'خانه های سبک زندگی',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 4,
    baths: 1,
    area: '1300 متر مربع',
    more: 4,
  }
];
export const albama = [
  {
    id: 1,
    image: house1,
    isFeatured: false,
    title: 'خانه خانوادگی لوکس در کنار ساحل',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 3,
    baths: 3,
    area: '1400 متر مربع',
    more: 1,
  },
  {
    id: 2,
    image: house2,
    isFeatured: false,
    title: 'سمت ساحل ویلا ',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 2,
    baths: 2,
    area: '1100 متر مربع',
    more: 2,
  },
  {
    id: 3,
    image: house3,
    isFeatured: false,
    title: 'خانه های سبک زندگی',
    subTitle: 'خیابان جنوبی غربی',
    name: 'نیما عزیزی',
    date: '2 روز پیش',
    prize: '1000000 ریال',
    sqft: 'ریال 587/متر مربع',
    bedrooms: 4,
    baths: 1,
    area: '1300 متر مربع',
    more: 4,
  }
];
